### PR TITLE
RCB_and_Playoffs.c

### PR DESCRIPTION
**Pull request by gulshanjakhon**
This is a problem from CodeChef | Competitive Programming :
Question :  
          Team RCB has earned X points in the games it has played so far in this year's IPL. To qualify for the playoffs they must earn at least a total of Y points. They currently have Z games left, in each game they earn 2 points for a win, 1 point for a draw, and no points for a loss.

Is it possible for RCB to qualify for the playoffs this year?

Sample Input 1 : 
3
4 10 8
3 6 1 
4 8 2 
Sample Output 1 :
YES
NO
YES

### CODE REVIEW

**Comment by gulshanjakhon** [comment]
please check now !

**Comment by gulshanjakhon** [comment]
Why it shows **Excluded Project** in my hacktoberfest profile ..

**Comment by SR-Sunny-Raj** [comment]
> Why it shows **Excluded Project** in my hacktoberfest profile ..

This project had been excluded because of spamming pull requests.

**Comment by gulshanjakhon** [comment]
Then what i do next ?

**Pull request merged**
