### PR TITLE
added new solution to DP, Array, Linked List, String and Matrix

### PR DESCRIPTION
**Pull request by Aryavir07**
New Solutions to following problems:
— Rotate matrix/Image
— Russian Doll Envelope 
— Add two numbers
— The Largest Number 
and few more

### CODE REVIEW

**Comment by SR-Sunny-Raj** [comment]
@Aryavir07 Great Work there. Keep it up👍🏻

**Comment by Aryavir07** [comment]
@SR-Sunny-Raj why my name is appearing as contributor?

**Comment by SR-Sunny-Raj** [comment]
@Aryavir07 bro you contributed your program into this repo that's why it's showing your name as a contributor.

**Comment by Aryavir07** [comment]
My bad, Its not showing my name as contributor that what I meant :(

**Pull request merged**
