### PR TITLE
Program to Capitalise first letter of a string.

### PR DESCRIPTION
**Pull request by malyabansalper**

### CODE REVIEW

**Comment by SR-Sunny-Raj** [comment]
@malyabansalper Please add your program to the Python Program folder in of this repository.

**Comment by malyabansalper** [comment]
Okay sure. Thanks for the suggestion.

**Comment by malyabansalper** [comment]
Please review I have made the required changes.

**Comment by SR-Sunny-Raj** [comment]
> Please review I have made the required changes.

@malyabansalper You need not to change the file name. There's already a folder named Python Programs in the repository, you just need to add your program there.

**Comment by malyabansalper** [comment]
I really cant locate the folder. Its not visible to me

**Comment by SR-Sunny-Raj** [comment]
> I really cant locate the folder. Its not visible to me

It's the 33th folder in this repo.  Here's the [link](https://github.com/SR-Sunny-Raj/Hacktoberfest2021-DSA/tree/master/33.%20Python%20Programs)

**Comment by malyabansalper** [comment]
I am unable to do it please provide some guidance.

**Comment by malyabansalper** [comment]
When I have forked I am not getting that folder in my copy of the repository . further I tried to fork it again but same problem couldn't get that folder in my forked copy.

**Comment by SR-Sunny-Raj** [comment]
> When I have forked I am not getting that folder in my copy of the repository . further I tried to fork it again but same problem couldn't get that folder in my forked copy.

You can find it at this [link](https://github.com/SR-Sunny-Raj/Hacktoberfest2021-DSA/tree/master/33.%20Python%20Programs)

**Comment by noob0412** [comment]
Hey is this an open issue can I contribute to it.

**Comment by noob0412** [comment]
I want to know that do I have to do the issue in python only

**Comment by SR-Sunny-Raj** [comment]
> I want to know that do I have to do the issue in python only

No you can do your program in any language of your choice.

**Comment by malyabansalper** [comment]
Please review the changes I have added the program to string folder of this repo as this is an appropriate program that can be considered under that category.
Thank you and please merge the PR. I would be very grateful.

**Comment by SR-Sunny-Raj** [comment]
> Please review the changes I have added the program to string folder of this repo as this is an appropriate program that can be considered under that category. Thank you and please merge the PR. I would be very grateful.

Ohkk good👍🏻

**Comment by malyabansalper** [comment]
Please kindly mark it at hacktoberfest accepted

**Comment by SR-Sunny-Raj** [comment]
> Please kindly mark it at hacktoberfest accepted. I would be very grateful for that.

It's already marked.

**Comment by malyabansalper** [comment]
Okayy Thanks a lot.

**Pull request merged**
