### PR TITLE
atcoder 220 FG operations solution

### PR DESCRIPTION
**Pull request by manish7392**
please accept it as hacktoberfest-accepted label

### CODE REVIEW

**Comment by manish7392** [comment]
pleae do care here

**Comment by SR-Sunny-Raj** [comment]
Hey @manish7392 , Please provide the problem statement or the link to the problem along with your solution.

**Comment by manish7392** [comment]
hey thanks for your reply  . i have attached problem link also now.
//thanks

**Comment by SR-Sunny-Raj** [comment]
> hey thanks for your reply . i have attached problem link also now. //thanks

Great👍🏻

**Pull request merged**
