### PR TITLE
Create Longest Bitonic subsequence.md

### PR DESCRIPTION
**Pull request by busybee23**

### CODE REVIEW

**Comment by SR-Sunny-Raj** [comment]
@busybee23 Please provide proper file extension and make correction in your program accordingly.

**Comment by busybee23** [comment]
Sure, I'll make another one.

**Comment by busybee23** [comment]
updated both of them, please merge.

**Comment by SR-Sunny-Raj** [comment]
> updated both of them, please merge.

Great👍🏻

**Pull request merged**
